services:

  order-db:
    image: mysql:8.0
    container_name: order-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orderdb
      MYSQL_USER: orderuser
      MYSQL_PASSWORD: orderpass
    ports:
      - "3307:3306"
    volumes:
      - order-db-data:/var/lib/mysql

  payment-db:
    image: mysql:8.0
    container_name: payment-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paymentdb
      MYSQL_USER: paymentuser
      MYSQL_PASSWORD: paymentpass
    ports:
      - "3308:3306"
    volumes:
      - payment-db-data:/var/lib/mysql

volumes:
  order-db-data:
  payment-db-data:
